### PR TITLE
Switch to monorepo

### PR DESCRIPTION
**Pull request by hpnzm**
## What changes
- Use monorepo for easy developing 😅
- Accept user custom theme

### CODE REVIEW

**Comment by hpnzm** [comment]
Hi @Sajarin-M, can you review this PR, thanks

**Comment by Sajarin-M** [comment]
Hello @hpnzm , 

Thank you so much for your contribution! 👍. this really matters to me.
I'll give it a look and try to merge it soon as I can.  😊

**Comment by Sajarin-M** [comment]
Thanks 🤗

**Comment by hpnzm** [comment]
Thanks for merging @Sajarin-M ! Your plugin is truly fantastic. I'm really excited to contribute even more to its development. 😆

**Comment by Sajarin-M** [comment]
Thanks and Welcome

**Pull request merged**
